# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pract_2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(983, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 851, 531))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.stackedWidget.setPalette(palette)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.button_calculoRt = QtWidgets.QPushButton(self.page)
        self.button_calculoRt.setGeometry(QtCore.QRect(350, 410, 155, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_calculoRt.setPalette(palette)
        self.button_calculoRt.setObjectName("button_calculoRt")
        self.spinBox_Nc = QtWidgets.QSpinBox(self.page)
        self.spinBox_Nc.setGeometry(QtCore.QRect(350, 183, 61, 20))
        self.spinBox_Nc.setMaximum(999)
        self.spinBox_Nc.setObjectName("spinBox_Nc")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(160, 222, 158, 20))
        self.label_6.setObjectName("label_6")
        self.spinBox_Pll = QtWidgets.QDoubleSpinBox(self.page)
        self.spinBox_Pll.setGeometry(QtCore.QRect(350, 300, 61, 20))
        self.spinBox_Pll.setMaximum(100.0)
        self.spinBox_Pll.setSingleStep(0.01)
        self.spinBox_Pll.setObjectName("spinBox_Pll")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(160, 183, 158, 20))
        self.label_4.setObjectName("label_4")
        self.SpinBox_Tpll = QtWidgets.QDoubleSpinBox(self.page)
        self.SpinBox_Tpll.setGeometry(QtCore.QRect(350, 261, 61, 20))
        self.SpinBox_Tpll.setMaximum(999.99)
        self.SpinBox_Tpll.setSingleStep(0.01)
        self.SpinBox_Tpll.setObjectName("SpinBox_Tpll")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(160, 261, 158, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setGeometry(QtCore.QRect(160, 300, 158, 20))
        self.label_8.setObjectName("label_8")
        self.spinBox_Nl = QtWidgets.QSpinBox(self.page)
        self.spinBox_Nl.setGeometry(QtCore.QRect(350, 222, 61, 20))
        self.spinBox_Nl.setMaximum(999)
        self.spinBox_Nl.setObjectName("spinBox_Nl")
        self.label_13 = QtWidgets.QLabel(self.page)
        self.label_13.setGeometry(QtCore.QRect(510, 340, 81, 20))
        self.label_13.setObjectName("label_13")
        self.spinBox_BWres = QtWidgets.QDoubleSpinBox(self.page)
        self.spinBox_BWres.setGeometry(QtCore.QRect(350, 340, 61, 20))
        self.spinBox_BWres.setMaximum(9999.0)
        self.spinBox_BWres.setSingleStep(0.01)
        self.spinBox_BWres.setObjectName("spinBox_BWres")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(510, 260, 101, 20))
        self.label_11.setObjectName("label_11")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(160, 340, 179, 20))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setGeometry(QtCore.QRect(510, 300, 101, 20))
        self.label_12.setObjectName("label_12")
        self.spinBox_jitter = QtWidgets.QDoubleSpinBox(self.page)
        self.spinBox_jitter.setGeometry(QtCore.QRect(630, 340, 61, 20))
        self.spinBox_jitter.setMaximum(999.99)
        self.spinBox_jitter.setSingleStep(0.01)
        self.spinBox_jitter.setObjectName("spinBox_jitter")
        self.spinBox_Rt = QtWidgets.QDoubleSpinBox(self.page)
        self.spinBox_Rt.setGeometry(QtCore.QRect(630, 260, 61, 20))
        self.spinBox_Rt.setMaximum(999.99)
        self.spinBox_Rt.setSingleStep(0.01)
        self.spinBox_Rt.setObjectName("spinBox_Rt")
        self.spinBox_Rr = QtWidgets.QDoubleSpinBox(self.page)
        self.spinBox_Rr.setGeometry(QtCore.QRect(630, 300, 61, 20))
        self.spinBox_Rr.setMaximum(999.99)
        self.spinBox_Rr.setSingleStep(0.01)
        self.spinBox_Rr.setObjectName("spinBox_Rr")
        self.spinBox_MOS = QtWidgets.QSpinBox(self.page)
        self.spinBox_MOS.setGeometry(QtCore.QRect(542, 180, 51, 20))
        self.spinBox_MOS.setMinimum(1)
        self.spinBox_MOS.setMaximum(5)
        self.spinBox_MOS.setObjectName("spinBox_MOS")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(510, 180, 22, 20))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(160, 140, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(510, 140, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(510, 230, 41, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.button_calcularRt = QtWidgets.QPushButton(self.page_2)
        self.button_calcularRt.setGeometry(QtCore.QRect(370, 170, 81, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_calcularRt.setPalette(palette)
        self.button_calcularRt.setObjectName("button_calcularRt")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setGeometry(QtCore.QRect(240, 160, 131, 43))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_31 = QtWidgets.QLabel(self.page_2)
        self.label_31.setGeometry(QtCore.QRect(500, 160, 151, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_29 = QtWidgets.QLabel(self.page_2)
        self.label_29.setGeometry(QtCore.QRect(140, 220, 111, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.page_2)
        self.label_30.setGeometry(QtCore.QRect(150, 270, 91, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_RetardoTotal_15 = QtWidgets.QLabel(self.page_2)
        self.label_RetardoTotal_15.setGeometry(QtCore.QRect(280, 220, 131, 41))
        self.label_RetardoTotal_15.setText("")
        self.label_RetardoTotal_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoTotal_15.setObjectName("label_RetardoTotal_15")
        self.label_paquetesRTP_15 = QtWidgets.QLabel(self.page_2)
        self.label_paquetesRTP_15.setGeometry(QtCore.QRect(530, 220, 101, 31))
        self.label_paquetesRTP_15.setText("")
        self.label_paquetesRTP_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_paquetesRTP_15.setObjectName("label_paquetesRTP_15")
        self.label_RetardoTotal_2 = QtWidgets.QLabel(self.page_2)
        self.label_RetardoTotal_2.setGeometry(QtCore.QRect(280, 270, 131, 41))
        self.label_RetardoTotal_2.setText("")
        self.label_RetardoTotal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RetardoTotal_2.setObjectName("label_RetardoTotal_2")
        self.label_paquetesRTP_2 = QtWidgets.QLabel(self.page_2)
        self.label_paquetesRTP_2.setGeometry(QtCore.QRect(530, 280, 101, 31))
        self.label_paquetesRTP_2.setText("")
        self.label_paquetesRTP_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_paquetesRTP_2.setObjectName("label_paquetesRTP_2")
        self.button_siguiente = QtWidgets.QPushButton(self.page_2)
        self.button_siguiente.setGeometry(QtCore.QRect(600, 350, 101, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_siguiente.setPalette(palette)
        self.button_siguiente.setObjectName("button_siguiente")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(170, 200, 531, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(170, 260, 531, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setGeometry(QtCore.QRect(170, 310, 531, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.page_2)
        self.line_4.setGeometry(QtCore.QRect(460, 170, 20, 151))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.page_2)
        self.line_5.setGeometry(QtCore.QRect(220, 170, 20, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(170, 120, 101, 16))
        self.label_15.setObjectName("label_15")
        self.label_CODEC_2 = QtWidgets.QLabel(self.page_2)
        self.label_CODEC_2.setGeometry(QtCore.QRect(270, 110, 151, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_CODEC_2.setFont(font)
        self.label_CODEC_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_CODEC_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_CODEC_2.setLineWidth(3)
        self.label_CODEC_2.setText("")
        self.label_CODEC_2.setObjectName("label_CODEC_2")
        self.button_atras = QtWidgets.QPushButton(self.page_2)
        self.button_atras.setGeometry(QtCore.QRect(170, 350, 75, 23))
        self.button_atras.setObjectName("button_atras")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.button_BHT = QtWidgets.QPushButton(self.page_3)
        self.button_BHT.setGeometry(QtCore.QRect(80, 150, 131, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_BHT.setPalette(palette)
        self.button_BHT.setObjectName("button_BHT")
        self.label_BHT = QtWidgets.QLabel(self.page_3)
        self.label_BHT.setGeometry(QtCore.QRect(220, 150, 61, 21))
        self.label_BHT.setFrameShape(QtWidgets.QFrame.Box)
        self.label_BHT.setText("")
        self.label_BHT.setObjectName("label_BHT")
        self.label_53 = QtWidgets.QLabel(self.page_3)
        self.label_53.setGeometry(QtCore.QRect(50, 250, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_3)
        self.label_54.setGeometry(QtCore.QRect(50, 310, 61, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.button_BWll = QtWidgets.QPushButton(self.page_3)
        self.button_BWll.setGeometry(QtCore.QRect(150, 200, 81, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_BWll.setPalette(palette)
        self.button_BWll.setObjectName("button_BWll")
        self.label_BWll_RTP = QtWidgets.QLabel(self.page_3)
        self.label_BWll_RTP.setGeometry(QtCore.QRect(130, 260, 121, 31))
        self.label_BWll_RTP.setText("")
        self.label_BWll_RTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWll_RTP.setObjectName("label_BWll_RTP")
        self.label_BWll_cRTP = QtWidgets.QLabel(self.page_3)
        self.label_BWll_cRTP.setGeometry(QtCore.QRect(130, 300, 121, 41))
        self.label_BWll_cRTP.setText("")
        self.label_BWll_cRTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWll_cRTP.setObjectName("label_BWll_cRTP")
        self.button_BWSIPTRUNK = QtWidgets.QPushButton(self.page_3)
        self.button_BWSIPTRUNK.setGeometry(QtCore.QRect(300, 200, 81, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_BWSIPTRUNK.setPalette(palette)
        self.button_BWSIPTRUNK.setObjectName("button_BWSIPTRUNK")
        self.label_BWst_RTP = QtWidgets.QLabel(self.page_3)
        self.label_BWst_RTP.setGeometry(QtCore.QRect(290, 260, 111, 31))
        self.label_BWst_RTP.setText("")
        self.label_BWst_RTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWst_RTP.setWordWrap(True)
        self.label_BWst_RTP.setObjectName("label_BWst_RTP")
        self.label_BWst_cRTP = QtWidgets.QLabel(self.page_3)
        self.label_BWst_cRTP.setGeometry(QtCore.QRect(280, 300, 121, 41))
        self.label_BWst_cRTP.setText("")
        self.label_BWst_cRTP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BWst_cRTP.setObjectName("label_BWst_cRTP")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(80, 100, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.comboBox_CODEC = QtWidgets.QComboBox(self.page_3)
        self.comboBox_CODEC.setGeometry(QtCore.QRect(700, 170, 121, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.comboBox_CODEC.setPalette(palette)
        self.comboBox_CODEC.setObjectName("comboBox_CODEC")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.comboBox_CODEC.addItem("")
        self.label_56 = QtWidgets.QLabel(self.page_3)
        self.label_56.setGeometry(QtCore.QRect(470, 230, 261, 23))
        self.label_56.setObjectName("label_56")
        self.button_cambiarParametros = QtWidgets.QPushButton(self.page_3)
        self.button_cambiarParametros.setGeometry(QtCore.QRect(730, 230, 91, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 42, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.button_cambiarParametros.setPalette(palette)
        self.button_cambiarParametros.setObjectName("button_cambiarParametros")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(510, 100, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.line_6 = QtWidgets.QFrame(self.page_3)
        self.line_6.setGeometry(QtCore.QRect(60, 240, 341, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.page_3)
        self.line_7.setGeometry(QtCore.QRect(60, 290, 341, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.page_3)
        self.line_8.setGeometry(QtCore.QRect(110, 200, 20, 141))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.page_3)
        self.line_9.setGeometry(QtCore.QRect(260, 200, 20, 141))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.page_3)
        self.line_10.setGeometry(QtCore.QRect(440, 60, 16, 351))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_18 = QtWidgets.QLabel(self.page_3)
        self.label_18.setGeometry(QtCore.QRect(470, 150, 301, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(470, 170, 241, 21))
        self.label_19.setObjectName("label_19")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(170, 230, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(320, 230, 47, 13))
        self.label_14.setObjectName("label_14")
        self.button_correo = QtWidgets.QPushButton(self.page_3)
        self.button_correo.setGeometry(QtCore.QRect(600, 320, 91, 21))
        self.button_correo.setObjectName("button_correo")
        self.button_atras2 = QtWidgets.QPushButton(self.page_3)
        self.button_atras2.setGeometry(QtCore.QRect(150, 380, 75, 23))
        self.button_atras2.setObjectName("button_atras2")
        self.stackedWidget.addWidget(self.page_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 983, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_calculoRt.setText(_translate("MainWindow", "Calcular Rt"))
        self.label_6.setText(_translate("MainWindow", "Número de líneas por cliente (Nl)"))
        self.label_4.setText(_translate("MainWindow", "Número de empresas cliente (Nc)"))
        self.label_7.setText(_translate("MainWindow", "Tiempo medio de llamada (Tpll)"))
        self.label_8.setText(_translate("MainWindow", "Probabilidad llamada (Pll)"))
        self.label_13.setText(_translate("MainWindow", "Jitter total (J)"))
        self.label_11.setText(_translate("MainWindow", "Retardo total (Rt)"))
        self.label_10.setText(_translate("MainWindow", "Ancho de banda de reserva (BWres)"))
        self.label_12.setText(_translate("MainWindow", "Retardo de red (Rr)"))
        self.label.setText(_translate("MainWindow", "MOS"))
        self.label_3.setText(_translate("MainWindow", "Parámetros de la aplicación"))
        self.label_5.setText(_translate("MainWindow", "QoE"))
        self.label_9.setText(_translate("MainWindow", "QoS"))
        self.button_calcularRt.setText(_translate("MainWindow", "Calcular"))
        self.label_26.setText(_translate("MainWindow", "Retardo total (en ms)"))
        self.label_31.setText(_translate("MainWindow", "Paquetes RTP almacenados"))
        self.label_29.setText(_translate("MainWindow", "x1.5"))
        self.label_30.setText(_translate("MainWindow", "x2"))
        self.button_siguiente.setText(_translate("MainWindow", "Siguiente"))
        self.label_15.setText(_translate("MainWindow", "El codec elegido es:"))
        self.button_atras.setText(_translate("MainWindow", "Atrás"))
        self.button_BHT.setText(_translate("MainWindow", "Tráfico durante la BHT"))
        self.label_53.setText(_translate("MainWindow", "RTP"))
        self.label_54.setText(_translate("MainWindow", "cRTP"))
        self.button_BWll.setText(_translate("MainWindow", "BWII"))
        self.button_BWSIPTRUNK.setText(_translate("MainWindow", "BWst"))
        self.label_16.setText(_translate("MainWindow", "QoS y Ancho de Banda"))
        self.comboBox_CODEC.setItemText(0, _translate("MainWindow", "G.711 (64 Kbps)"))
        self.comboBox_CODEC.setItemText(1, _translate("MainWindow", "G.729 (8 Kbps)"))
        self.comboBox_CODEC.setItemText(2, _translate("MainWindow", "G.723.1 (6.3 Kbps)"))
        self.comboBox_CODEC.setItemText(3, _translate("MainWindow", "G.723.1 (5.3 Kbps)"))
        self.comboBox_CODEC.setItemText(4, _translate("MainWindow", "G.726 (32 Kbps)"))
        self.comboBox_CODEC.setItemText(5, _translate("MainWindow", "G.726 (24 Kbps)"))
        self.comboBox_CODEC.setItemText(6, _translate("MainWindow", "G.728 (16 Kbps)"))
        self.comboBox_CODEC.setItemText(7, _translate("MainWindow", "G.722_64k (64 Kbps)"))
        self.comboBox_CODEC.setItemText(8, _translate("MainWindow", "ilbc_mode_20 (15.2 Kbps)"))
        self.comboBox_CODEC.setItemText(9, _translate("MainWindow", "ilbc_mode_30 (13.33 Kbps)"))
        self.label_56.setText(_translate("MainWindow", "O si lo prefiere, cambiar los parametros de entrada:"))
        self.button_cambiarParametros.setText(_translate("MainWindow", "Volver al inicio"))
        self.label_17.setText(_translate("MainWindow", "Optimización"))
        self.label_18.setText(_translate("MainWindow", "Si no se cumplien los requisitos de QoE/QoS/GoS introducidos"))
        self.label_19.setText(_translate("MainWindow", " puede elegir otro códec y repetir los cálculos:"))
        self.label_2.setText(_translate("MainWindow", "En Kbps"))
        self.label_14.setText(_translate("MainWindow", "En Kbps"))
        self.button_correo.setText(_translate("MainWindow", "Enviar correo"))
        self.button_atras2.setText(_translate("MainWindow", "Atrás"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

